### ISSUE TITLE
Example suggestions

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe-examples#2]
#### Mocks
- [x] Mock Date - https://stackoverflow.com/a/55503853/10448174 (**DONE: https://github.com/DevExpress/testcafe-examples/tree/master/examples/mock-date**)
- [x] Setup access to microphone and camera API - https://stackoverflow.com/questions/58388177/browser-capabilities-in-testcafe (**DONE: https://github.com/DevExpress/testcafe-examples/tree/master/detached-examples/mock-camera-microphone-access**)

#### Actions
- [x] [Simulate scroll with hover or element.scrollIntoView()](https://stackoverflow.com/questions/58175461/how-to-scroll-up-and-scroll-down-using-testcafe) (**DONE: https://github.com/DevExpress/testcafe-examples/tree/master/examples/scroll**)

#### Download & Upload
- [x] How to upload a file with TestCafe: https://stackoverflow.com/search?q=%5Btestcafe%5D+Upload (**[DONE](https://github.com/DevExpress/testcafe-examples/tree/master/examples/upload-files)**)

 - [x] Wait for a file download ([1]( https://stackoverflow.com/questions/57582108/testcafe-example-to-assert-file-download), [2](https://stackoverflow.com/questions/58413354/download-xml-with-fixture), [3](https://stackoverflow.com/a/58543676/10448174)): (**[DONE](https://github.com/DevExpress/testcafe-examples/tree/master/examples/check-downloaded-file-name-and-content)**)
 - [x] Wait for a file download with a glob [[1](https://stackoverflow.com/questions/63350993/is-there-a-way-to-assert-download-file-with-partial-filename-in-testcafe)] ( **[DONE](https://github.com/DevExpress/testcafe-examples/tree/master/examples/check-downloaded-file-name-and-content)** )
 - [x] [How to check downloaded file name](https://stackoverflow.com/questions/58657559/how-to-check-downloaded-file-name) ( **[DONE](https://github.com/DevExpress/testcafe-examples/tree/master/examples/check-downloaded-file-name-and-content)** )
 
- [x] Check downloaded file content [1](
https://stackoverflow.com/questions/57582108/testcafe-example-to-assert-file-download), [2](https://stackoverflow.com/questions/58413354/download-xml-with-fixture), [3](https://stackoverflow.com/questions/58541282/timeout-while-file-download) (**[DONE](https://github.com/DevExpress/testcafe-examples/tree/master/examples/check-downloaded-file-name-and-content)**)

#### Request Mocks
 - [x] Use Request Logger to log REST API calls: https://stackoverflow.com/questions/52745697/requestlogger-not-intercepting-all-http-requests  **([DONE](https://github.com/DevExpress/testcafe-examples/tree/master/examples/check-if-image-loaded))**
- [x] [How to add request logger for a test or a fixture and filter logs by a browser](https://github.com/DevExpress/testcafe/issues/4616) (**POSTPONED: #34** )
- [x] [Set referrer with RequestHook](https://stackoverflow.com/questions/61116376/set-referrer-for-firefox-on-test-cafe) [Draft](https://github.com/DevExpress/testcafe-examples/issues/2#issuecomment-611497001) ([**DONE**](https://github.com/DevExpress/testcafe-examples/pull/36))
- [x] Additional examples:
\+ https://stackoverflow.com/questions/59414705/test-cafe-how-to-modify-or-inject-data-into-a-response [**Won't do. The feature is not released -https://github.com/DevExpress/testcafe/issues/2991**]
\+ https://stackoverflow.com/questions/56556487/testcafe-how-to-read-json-response-and-pick-first-item-and-pass-it-to-selector [**Won't do. The task is not related to TestCafe**]
\+ https://stackoverflow.com/questions/57002221/mock-api-to-give-response-based-on-request-urls-dynamic-part [**Moved to https://github.com/DevExpress/testcafe-examples/issues/43**]

#### Selectors (**DONE: https://github.com/DevExpress/testcafe-examples/pull/28**)
- [x] [xpath Selector](https://stackoverflow.com/a/55627672/10448174)
- [x] Advanced CSS selectors: [by attribute](https://stackoverflow.com/questions/58220775/catching-data-attributes-in-testcafe) (**Won't do: user's typo**)
- [x] XPath selector with filters: [nth](https://stackoverflow.com/questions/55624944/how-to-get-first-occurrence-of-the-element-from-multiple-match-found-in-testcafe)
-[ ] CSS selectors with filters: [nth](https://stackoverflow.com/questions/57842930/understanding-selector-nth) (**Won't do: standard operation, example not required**)
- [x] [Selectors with dynamic classes and IDs](https://stackoverflow.com/questions/59371277/testcafe-web-application-xaf-application-with-dynamic-ids) [2](https://stackoverflow.com/questions/56918787/using-js-dynamic-variables-in-fixture) (**Won't do, we have an [article](https://devexpress.github.io/testcafe/documentation/guides/basic-guides/select-page-elements.html#select-elements-with-dynamic-ids)**)
- [x] Add framework-specific selector examples: Angular [1](https://stackoverflow.com/questions/54837179/test-fails-because-angularjs-has-not-initialized-in-time), [2](https://stackoverflow.com/questions/54875091/waiting-for-angularjs-initialization-after-using-navigateto ), [React](https://stackoverflow.com/questions/55028357/trouble-finding-element-node-using-testcafe-selector-or-testcafe-react-selector) (**Won't do, we have dedicated repos for the frameworks: [react](https://github.com/devexpress/testcafe-react-selectors), [Vue](https://github.com/devexpress/testcafe-vue-selectors), [Angular](https://github.com/devexpress/testcafe-angular-selectors)**)
- [x] Iterate over elements of a list [1](https://stackoverflow.com/questions/57457936/how-can-one-add-2-constants-on-1-possible-parameters-in-a-testcafe-assertion), [2](https://stackoverflow.com/questions/54912825/testcaf%c3%a9-verify-that-all-the-categories-are-displayed-and-the-total-score )
- [x] [Selecting table elements by cell content](https://stackoverflow.com/questions/56415647/how-to-click-an-element-of-a-table-row-that-has-a-column-with-specific-text) [2](https://stackoverflow.com/questions/54910527/selecting-elements-from-dom)
- [x] [Handling color input values](https://stackoverflow.com/questions/57431933/evaluate-color-change-with-testcafe)(**Won't do: basic functionality**)
- [x] Advanced DOM Snapshot methods: [getAttributes](https://stackoverflow.com/questions/58135564/how-do-you-compare-selector-attributes-in-testcafe) (**Won't do, described [here](https://devexpress.github.io/testcafe/documentation/reference/test-api/domnodestate.html#members-specific-to-element-nodes)**)
- [x] Selectors for complex DOM trees: (**Won't do: described in the [docs](https://devexpress.github.io/testcafe/documentation/reference/test-api/selector/sibling.html)**)
\+ https://stackoverflow.com/questions/55067909/select-a-child-element-from-a-parent-using-a-cousin-node-of-the-same-parent
\+ https://stackoverflow.com/questions/57485741/selector-definition-with-testcafe
 - [x] Store CSS string of a Selector and use it afterwards

#### ClientFunction **(DONE: https://github.com/DevExpress/testcafe-examples/pull/22)**
- [x] Wait for a built-in page object property value - https://stackoverflow.com/questions/58373482/wait-for-css-property/58380117#58380117
 - [x] Check if the document in the `iframe` is loaded using `ClientFunction`:
https://stackoverflow.com/questions/57787520/interacting-with-iframe-with-empty-src-attribute/57819981#57819981

- [x] [How can my application code know whether the app is being tested with testcafe?](https://stackoverflow.com/questions/55425982/how-can-my-application-code-know-whether-the-app-is-being-tested-with-testcafe) (**DONE: https://github.com/DevExpress/testcafe-examples/pull/26**)
- [x] Additional ClientFunction examples:
\+ [show/hide an element](https://stackoverflow.com/questions/58216736/testcafe-ignore-overlaying-element )
\+ [with an argument](https://stackoverflow.com/questions/55306249/testcafe-clientfunction-to-set-video-currenttime-property)
\+ https://stackoverflow.com/questions/54231741/how-to-remove-style-properties-in-testcafe 
\+ https://stackoverflow.com/questions/55643047/how-to-select-div-with-pseudoelement-after-in-testcafe 
\+ https://stackoverflow.com/questions/56132480/run-command-in-the-browsers-console-during-the-test-in-testcafe 

#### ClientScripts
- [x] Adding a module with ClientScripts and using its API with ClientFunction [[1](https://stackoverflow.com/questions/60961748/clientfunction-axios2-is-not-defined)] ( **[DONE](https://github.com/DevExpress/testcafe-examples/blob/master/examples/client-scripts/inject-a-nodejs-module.js)** )
- [x] [How to capture client-side errors on a page](https://stackoverflow.com/questions/57399515/accumulate-all-js-warnings-and-errors-during-test-runs-in-testcafe) (**DONE: https://github.com/DevExpress/testcafe-examples/pull/24**)

#### Runner & CLI
- [x] [How do I run tests on multiple browsers in lambdatest?](https://stackoverflow.com/questions/61404131/how-do-i-run-tests-on-multiple-browsers-in-lambdatest) (**Won't do, example available [here](https://github.com/LambdaTest/testcafe-sample)** )
- [x] Pass arguments to tests [[1](https://stackoverflow.com/questions/58075755/how-can-i-inject-parameters-into-a-testcaf%c3%a9-test ) (**DONE: https://github.com/DevExpress/testcafe-examples/pull/28**)

#### Uncategorized Scenarios
- [x] Test features that require a secure context - Web Crypto, Service Workers, Apple Pay. [Which pages Chrome considers secure](https://chromium.googlesource.com/chromium/src/+/master/docs/security/faq.md#which-origins-are-secure)[**Done - https://github.com/DevExpress/testcafe-examples/tree/master/detached-examples/mock-camera-microphone-access**]
 - [x] Windows and basic authentication example - https://supportcenter.devexpress.com/internal/ticket/details/T809667 [**Won't do. Customer set wrong credentials**]
- [x] [Progress bar testing example](
https://stackoverflow.com/questions/61614885/how-to-test-dymamic-progress-bar-using-testcafe) [**Done - https://github.com/DevExpress/testcafe-examples/tree/master/examples/wait-for-element-property-value**]
- [x] Different timeout examples: selector, assertion [[1](https://stackoverflow.com/questions/61586874/testcafe-selecting-checkbox-using-id-always-end-up-with-the-full-timeout-wait )], [[2](https://stackoverflow.com/questions/58667119/is-there-a-way-in-testcafe-to-get-the-load-time-of-specific-page-elements/58762984#58762984 )][**Won't do. Customer don't specify the timeout property**]
- [x] [Random Data Generation](https://supportcenter.devexpress.com/internal/ticket/details/T697405)
\+ [https://stackoverflow.com/questions/1349404/generate-random-string-characters-in-javascript] (**Moved to https://github.com/DevExpress/testcafe-examples/issues/42**)(https://stackoverflow.com/questions/1349404/generate-random-string-characters-in-javascript)
\+ [https://stackoverflow.com/questions/1527803/generating-random-whole-numbers-in-javascript-in-a-specific-range](https://stackoverflow.com/questions/1527803/generating-random-whole-numbers-in-javascript-in-a-specific-range)
- [x] Using assertions in page object methods [[1](https://stackoverflow.com/questions/54936657/sharing-assertions-inside-page-object-methods )] (**Won't do: user's typo**)
- [x] Simulate the web page going to the background [[1](https://github.com/DevExpress/testcafe/issues/5465)] (**[DONE](https://github.com/DevExpress/testcafe-examples/tree/master/examples/blur-window)**)

**Comment by AlexKamaev** [comment]
How about this one? https://stackoverflow.com/questions/58373482/wait-for-css-property/58380117#58380117

**Comment by miherlosev** [comment]
It's good example. But I recommend to rename it as `Wait for a built-in page object property value` or simplified variant `Wait for ...`.

**Comment by kirovboris** [comment]
Test email sent via a test case
https://stackoverflow.com/questions/60179445/testcafe-any-recipes-available-for-email-integration

**Comment by AlexKamaev** [comment]
What about this one https://stackoverflow.com/questions/61116376/set-referrer-for-firefox-on-test-cafe
```JS
import { RequestHook } from 'testcafe';

fixture `fixture`
    .page `http://example.com`;


export class MyRequestHook extends RequestHook {
    constructor (requestFilterRules, responseEventConfigureOpts) {
        super(requestFilterRules, responseEventConfigureOpts);
    }
    async onRequest (event) {
        event.requestOptions.headers['Referer'] = 'http://my-modified-referer.com';
    }
    async onResponse (event) {
    }
}

const hook = new MyRequestHook();

test.requestHooks(hook)('referer', async t => {
    await t.navigateTo('https://www.whatismyreferer.com/');

    await t.debug();
});

```

**Comment by Farfurix** [comment]
Progress bar testing example:
https://stackoverflow.com/questions/61614885/how-to-test-dymamic-progress-bar-using-testcafe

**Comment by AlexSkorkin** [comment]
- [ ] [Random Data Generation](https://supportcenter.devexpress.com/internal/ticket/details/T697405)

+ [https://stackoverflow.com/questions/1349404/generate-random-string-characters-in-javascript](https://stackoverflow.com/questions/1349404/generate-random-string-characters-in-javascript)
+ [https://stackoverflow.com/questions/1527803/generating-random-whole-numbers-in-javascript-in-a-specific-range](https://stackoverflow.com/questions/1527803/generating-random-whole-numbers-in-javascript-in-a-specific-range)

- [ ] [How to capture client-side errors on a page](https://stackoverflow.com/questions/57399515/accumulate-all-js-warnings-and-errors-during-test-runs-in-testcafe)

- [ ] [How can my application code know whether the app is being tested with testcafe?](https://stackoverflow.com/questions/55425982/how-can-my-application-code-know-whether-the-app-is-being-tested-with-testcafe)

- [ ] [How to click unrendered virtualized element in TestCafe](https://stackoverflow.com/questions/59361825/how-to-click-unrendered-virtualized-element-in-testcafe)

- [ ] [How to add request logger for a test or a fixture and filter logs by a browser](https://github.com/DevExpress/testcafe/issues/4616)

- [ ] [TestCafe with Electron: show and hide main window](https://stackoverflow.com/questions/58386602/testcafe-with-electron-show-and-hide-main-window)

- [ ] [How to check downloaded file name?](https://stackoverflow.com/questions/58657559/how-to-check-downloaded-file-name)

- [ ] [Conditional testing](https://stackoverflow.com/questions/58843559/create-bootstrap-selector)

- [ ] [Selectors with dynamic classes and IDs](https://stackoverflow.com/questions/59371277/testcafe-web-application-xaf-application-with-dynamic-ids)

- [ ] [How do I run tests on multiple browsers in lambdatest?](https://stackoverflow.com/questions/61404131/how-do-i-run-tests-on-multiple-browsers-in-lambdatest)

**Comment by miherlosev** [comment]
QR Code from programmatic API - https://github.com/DevExpress/testcafe/issues/5528#issuecomment-690929810
